# Offense count: 1
# Configuration parameters: CountComments, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Max: 58

# Offense count: 1
# Configuration parameters: AllowedChars.
Style/AsciiComments:
  Exclude:
    - 'lib/sfst.rb'

# Offense count: 2
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/sfst.rb'
    - 'lib/sfst/version.rb'

# Offense count: 1
# Configuration parameters: AllowedVariables.
Style/GlobalVars:
  Exclude:
    - 'ext/sfst/extconf.rb'
