language: ruby

vm:
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.1

matrix:
  include:
    - name: macOS
      os: osx
      osx_image: xcode11
      compiler: clang
    - name: Xenial clang
      os: linux
      dist: xenial
      compiler: clang
    - name: Xenial gcc
      os: linux
      dist: xenial
      compiler: gcc

before_install: gem install bundler -v 2.1.4

script:
  - rake
  - echo "Rubocop $(bundle exec rubocop --version)"
  - bundle exec rubocop -S -E
