# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ruby-sfst"
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marius L. J\u{f8}hndal"]
  s.date = "2013-04-09"
  s.description = "A wrapper for the Stuttgart Finite State Transducer Tools (SFST)."
  s.email = "mariuslj (at) ifi [dot] uio (dot) no"
  s.extensions = ["ext/sfst_machine/extconf.rb"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG",
    "Manifest",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "ext/sfst_machine/.gitignore",
    "ext/sfst_machine/alphabet.C",
    "ext/sfst_machine/alphabet.h",
    "ext/sfst_machine/basic.C",
    "ext/sfst_machine/basic.h",
    "ext/sfst_machine/compact.C",
    "ext/sfst_machine/compact.h",
    "ext/sfst_machine/determinise.C",
    "ext/sfst_machine/extconf.rb",
    "ext/sfst_machine/fst-compiler.C",
    "ext/sfst_machine/fst-compiler.h",
    "ext/sfst_machine/fst-compiler.yy",
    "ext/sfst_machine/fst.C",
    "ext/sfst_machine/fst.h",
    "ext/sfst_machine/interface.C",
    "ext/sfst_machine/interface.h",
    "ext/sfst_machine/make-compact.C",
    "ext/sfst_machine/make-compact.h",
    "ext/sfst_machine/mem.h",
    "ext/sfst_machine/operators.C",
    "ext/sfst_machine/sfst_machine.cc",
    "ext/sfst_machine/sgi.h",
    "ext/sfst_machine/utf8-scanner.C",
    "ext/sfst_machine/utf8-scanner.ll",
    "ext/sfst_machine/utf8.C",
    "ext/sfst_machine/utf8.h",
    "lib/.gitignore",
    "lib/sfst.rb",
    "ruby-sfst.gemspec",
    "test/.gitignore",
    "test/test_sfst.fst",
    "test/test_sfst.rb"
  ]
  s.homepage = "http://github.com/mlj/ruby-sfst"
  s.require_paths = ["lib"]
  s.rubyforge_project = "sfst"
  s.rubygems_version = "1.8.23"
  s.summary = "Stuttgart Finite State Transducer Tools interface"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

