
# Gem::Specification for Ruby-sfst-0.0.1
# Originally generated by Echoe

--- !ruby/object:Gem::Specification 
name: ruby-sfst
version: !ruby/object:Gem::Version 
  version: 0.0.1
platform: ruby
authors: 
- "Marius L. J\xC3\xB8hndal"
autorequire: 
bindir: bin

date: 2008-07-29 00:00:00 +02:00
default_executable: 
dependencies: 
- !ruby/object:Gem::Dependency 
  name: echoe
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
description: A wrapper for the Stuttgart Finite State Transducer Tools (SFST).
email: mariuslj (at) ifi [dot] uio (dot) no
executables: []

extensions: 
- ext/sfst_machine/extconf.rb
extra_rdoc_files: 
- README.rdoc
- lib/sfst.rb
files: 
- README.rdoc
- Rakefile
- Manifest
- test/test_sfst.rb
- test/test_sfst.fst
- CHANGELOG
- ext/sfst_machine/fst-compiler.h
- ext/sfst_machine/utf8.C
- ext/sfst_machine/operators.C
- ext/sfst_machine/utf8-scanner.ll
- ext/sfst_machine/determinise.C
- ext/sfst_machine/interface.C
- ext/sfst_machine/compact.h
- ext/sfst_machine/basic.h
- ext/sfst_machine/fst.h
- ext/sfst_machine/make-compact.h
- ext/sfst_machine/fst-compiler.yy
- ext/sfst_machine/mem.h
- ext/sfst_machine/compact.C
- ext/sfst_machine/basic.C
- ext/sfst_machine/interface.h
- ext/sfst_machine/sfst_machine.cc
- ext/sfst_machine/extconf.rb
- ext/sfst_machine/alphabet.C
- ext/sfst_machine/fst.C
- ext/sfst_machine/alphabet.h
- ext/sfst_machine/make-compact.C
- ext/sfst_machine/fst-compiler.C
- ext/sfst_machine/utf8.h
- ext/sfst_machine/utf8-scanner.C
- lib/sfst.rb
- ruby-sfst.gemspec
has_rdoc: true
homepage: http://github.com/mlj/ruby-sfst
post_install_message: 
rdoc_options: 
- --line-numbers
- --inline-source
- --title
- Ruby-sfst
- --main
- README.rdoc
require_paths: 
- lib
- ext
required_ruby_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "0"
  version: 
required_rubygems_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - "="
    - !ruby/object:Gem::Version 
      version: "1.2"
  version: 
requirements: []

rubyforge_project: ruby-sfst
rubygems_version: 1.2.0
specification_version: 2
summary: A wrapper for the Stuttgart Finite State Transducer Tools (SFST).
test_files: 
- test/test_sfst.rb
